services:
  - type: web
    name: daily-doodle-cat
    env: node
    buildCommand: |
      echo "Build starting in: $(pwd)"
      ls -la
      if [ ! -f "package.json" ]; then
        echo "ERROR: package.json not found"
        exit 1
      fi
      npm ci
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        fromSecret: GEMINI_API_KEY
    plan: free