services:
  - type: web
    name: daily-doodle-cat
    env: node
    buildCommand: node deploy.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        fromSecret: GEMINI_API_KEY
    plan: free